version: '3.8'

services:
  web:
    build: .
    command: sh -c "cd /app/ft_transcendence && 
                    python manage.py migrate && 
                    python manage.py collectstatic --noinput --clear && 
                    daphne -p 8000 -b 0.0.0.0 ft_transcendence.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PYTHONPATH=/app/ft_transcendence
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persist Redis data
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./ft_transcendence/media:/app/media:ro
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data: