version: '3.8'

services:
  web:
    build: .
    command:
      sh -c "cd ft_transcendence &&
             python manage.py migrate &&
             uvicorn ft_transcendence.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PYTHONPATH=/app/ft_transcendence
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: